DROP DATABASE IF EXISTS TESTE_BD;
CREATE DATABASE IF NOT EXISTS TESTE_DB;
USE TESTE_DB;


DROP TABLE IF EXISTS versao_db;

CREATE TABLE IF NOT EXISTS versao_db (
id INT PRIMARY KEY AUTO_INCREMENT,
versao VARCHAR(32),
datahora_instalacao  DATETIME,
)
COMMENT ''
;