DROP TABLE IF EXISTS ajuda;
DROP TABLE IF EXISTS dica;
DROP TABLE IF EXISTS sobre;

CREATE TABLE IF NOT EXISTS ajuda (
id INT PRIMARY KEY AUTO_INCREMENT,
referente VARCHAR(32) COMMENT 'referente ao funcao', 
descricao VARCHAR(255),
ativo BOOLEAN
)
COMMENT ''
;

CREATE TABLE IF NOT EXISTS dica (
id INT PRIMARY KEY AUTO_INCREMENT,
descricao VARCHAR(255),
ativo BOOLEAN
)
COMMENT ''
;


CREATE TABLE IF NOT EXISTS sobre (
id INT PRIMARY KEY AUTO_INCREMENT,
descricao VARCHAR(255),
ativo BOOLEAN
)
COMMENT ''
;



